# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "/"
languageCode = "en-AU"
title = "Welcome to SchoolCoin!"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Metadata
[params]
  author = "Thomas Groh"
  description = "SchoolCoin is a secure low-fee conduit to privately & anonymously send money anywhere you have internet"

# Hero section (from here on is for icon theme)
[params.hero]
  img = "images/hero_bg.jpg"
  title = "School`Coin <br> A clear path to the privacy & security of your digtal money!"
  description = "Based on [Cryptonote](https://cryptonote.org/) technology"

# Navigation section
[params.nav]
  mission = "Our Mission"
  services = "Services"
  team = "The Team"
  contact = "Get In Touch"
  # Include logo instead if HOME:
  # logo = "path/to/logo"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "images/img_3.jpg"
    [[params.mission.images.list]]
      img = "images/img_2.jpg"
    [[params.mission.images.list]]
      img = "images/img_1.jpg"
    [[params.mission.images.list]]
      img = "images/img_4.jpg"

  [[params.mission.item]]
    weight = 1
    name = "marketing"
    title = "Marketing"
    subtitle = "Social media is a big part of our lives, and the existence of crypto platforms have boosted cryptocurrency in a unique way. Most of the value derives from how we envision it from the internet."
    description = "<p>The technical know-how and experience of a team is the backbone in every crypto project that wants to have a bright, long future. You can't expect the whitepaper, roadmap or even the finished product to sell itself. A superior online marketing strategy, with a clear and open communication about it's practical use case, will help differentiate the project apart from all others.</p><ul class='checked'><li>Practical Use Cases </li><li>Privacy & Anonymity </li><li>Protection & Security </li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 2
    name = "analysis"
    title = "Resources"
    subtitle = "Quam quasi illum expedita dicta nemo fugit reprehenderit similique! Corporis praesentium magnam sequi."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo, molestiae eaque fugiat dolores est esse, doloremque placeat assumenda corrupti officia dolorum. Sunt saepe ut, explicabo consectetur, nostrum illo est.</p><ul class='checked'><li>Free HTML5 Templates</li><li>Free Bootstrap Templates</li><li>Free HTML5 Bootstrap Templates</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 3
    name = "strategy"
    title = "Strategy"
    subtitle = "Magnam iste obcaecati illo laboriosam amet. Dignissimos sed quis voluptatum corporis adipisci amet."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio dolore illum expedita placeat debitis, dignissimos obcaecati et modi. Possimus id dicta consequuntur veritatis, reiciendis at expedita voluptate sint distinctio eligendi!</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

# Services section
[params.services]
  enable = true
  video = true
  vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "Our Services"
  description = "A digital currency like USD that can be exchanged between two entities, the difference with SchoolCoin's currency, it's made to be private, secure and anonymous using Blockchain technology by CryptoNote."

  [[params.services.item]]
    icon = "icon-ban"
    title = "Anonymous Transactions"
    description = "SchoolCoin allows anonymity by using Ring Signatures to hide wallet balances and transactions, making any transaction you make effectively unlinkable."

  [[params.services.item]]
    icon = "icon-eye"
    title = "Privacy Ready"
    description = "Your privacy is secured when it uses dual-key stealth address which require all four keys for complete functionality. More information on the Cryptonote protocol can be found on the Cryptonote whitepaper."

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Light Speed"
    description = "Using CryptoNote technology enables protection against double spending, analysis resistance, Prog-POW concept, and a difficulty target of 120 seconds per block allows for lite speed transactions."

  [[params.services.item]]
    icon = "icon-lock"
    title = "Cryptography"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-money"
    title = "Simple Wallet"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-support"
    title = "Customer Support"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# Work section
[params.work]
  enable = true

  [[params.work.item]]
    title = "Quarter One"
    subtitle = "2019"
    img = "images/img_1.jpg"

  [[params.work.item]]
    title = "Quarter Two"
    subtitle = "2019"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Quarter Three"
    subtitle = "2019"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Quarter four"
    subtitle = "2019"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Quarter One"
    subtitle = "2020"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Quarter Two"
    subtitle = "2020"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Quarter Three"
    subtitle = "2020"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Quarter Four"
    subtitle = "2020"
    img = "images/img_4.jpg"

# Team section
[params.team]
  enable = true
  title = "Meet The Team"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.team.item]]
    name = "Jean Doe"
    position = "Chief legend"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person1.jpg"
    facebook = "#"
    twitter = "#"
    linkedin = "#"
    instagram = "#"
    github = "#"
    

  [[params.team.item]]
    name = "Alice Doe"
    position = "Chief overlord"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person2.jpg"
    facebook = "#"
    twitter = "#"
    linkedin = "#"
    instagram = "#"
    github = "#"

  [[params.team.item]]
    name = "John Doe"
    position = "Chief haranguer"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person3.jpg"
    facebook = "#"
    twitter = "#"
    linkedin = "#"
    instagram = "#"
    github = "#"
    
    [[params.team.item]]
    name = "John Doe"
    position = "Chief haranguer"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person3.jpg"
    facebook = "#"
    twitter = "#"
    linkedin = "#"
    instagram = "#"
    github = "#"
    
    [[params.team.item]]
    name = "Alice Doe"
    position = "Chief overlord"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person2.jpg"
    facebook = "#"
    twitter = "#"
    linkedin = "#"
    instagram = "#"
    github = "#"
    
    [[params.team.item]]
    name = "Jean Doe"
    position = "Chief legend"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
    img = "images/person1.jpg"
    facebook = "#"
    twitter = "#"
    linkedin = "#"
    instagram = "#"
    github = "#"

# Contact section
[params.contact]
  enable = true
  title = "Get In Touch"
  message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."
  name_placeholder = "Your name"
  email_placeholder = "Your email"
  email_disclaimer = "We'll never share your email with anyone else."
  message_placeholder = "Please enter a message."
  button_text = "Submit"

# Footer section
[params.footer]
  enable = true
  note = "<p><small>&copy; 2018 SchoolCoin. All Rights Reserved. </small></p>"
  github = "https://github.com/school-coin/SchoolCoin"
  twitter = "#"
  facebook = "#"
  vine = "#"
  linkedin = "#"
  instagram = "#"
  
